### ISSUE TITLE
[1.21.1] Sidedness issue when loaded on a dedicated server

### ISSUE THREAD

**Issue by ProsperCraft** [DePhoegon/chococraft-delbase_patch#2]
https://gist.github.com/ProsperCraft/f1913468ea1baec3b1c269022a744b03

**Comment by DePhoegon** [comment]
First off, Thank you.

Found the problem & uploading the updated curse Forge listing.
-- Fix is in 3.3.1+ (Chocobos, for 1.20 / 1.20.1) https://legacy.curseforge.com/minecraft/mc-mods/dephoegons-chocobos/files/4608841

Future updates coming to address MP things.

Thank you and please do keep an eye out for it to update again.
-- Working on chocobo logic (to allow a distance to be set in a localized wonder
-- Working on despawning non-tamed chocobo & chocob that came from an egg (either breeding or spawn egg)
-- Updated values for Max limits on Str, armor, armor toughness,

There is one bug fix that is coming in down the line. (there is a client crash for accessing a value from the config file, if the access is too slow) -- This is fixed & will be tested more thoroughly. (even after the fix gets put in place)
-- The Server is unaffected by this one.

Do have a great day.
